### ISSUE TITLE
Indefinite Loading upon third-party API use

### ISSUE THREAD

**Issue by ekleinem** [spmdrd/plasma-applet-cryptocurrency-price#1]
I'm trying to use https://api.coinmarketcap.com/v1/ticker/hush/

This API has "price_usd" that I'm trying to use.

I get $nan with price_usd in the JSON key field, and indefinite loading when I use [0].price_usd or 0.price_usd.

I'm a newb to APIs and JSON but I don't know what I could be doing wrong here.

I'd appreciate any help, thanks!

**Comment by spmdrd** [comment]
sorry about that. fixed it so [0].price_usd works now.
