### ISSUE TITLE
[Feature Request] Presets

### ISSUE THREAD

**Issue by JuniorJPDJ** [spmdrd/plasma-applet-cryptocurrency-price#2]
Hi,
Maybe you would like to add some presets with working settings? (like in original widget)
You can just copy it from original widget :D

**Comment by spmdrd** [comment]
This is definitely something i'd like to do but I haven't figured out a way to maintain such an ever changing list in my spare time (exchanges are constantly popping up, going under and changing their api urls/key formats). Will have to think on a solution.

**Comment by spmdrd** [comment]
added a few presets as of v1.4.
