### ISSUE TITLE
[BUG] BIIIIIG CPU usage when no internet connection while refreshing

### ISSUE THREAD

**Issue by JuniorJPDJ** [spmdrd/plasma-applet-cryptocurrency-price#4]
Hi,
I've got BIIIIIG CPU usage by plasma-shell process when there is no internet connection or other error, (like malformed response from exchange) while refreshing price.
ATM deleted your widget from my desktop :/

Similar issue at upstream:
https://github.com/MakG10/plasma-applet-bitcoin-price/issues/5

**Comment by spmdrd** [comment]
I have not been able to replicate this issue. Please provide more info and/or steps to duplicate.

**Comment by spmdrd** [comment]
no follow up from issue reporter.

**Comment by wincak** [comment]
This happens to me as well sometimes. If there is none or intermittent Internet connection, the widget continues to try to refresh indefinitely (spinning animation). This seems to lead to high CPU usage.

How to reproduce:
1) Launch htop to see CPU usage
2) Disconnect Internet connection
3) Right click widget -> Refresh
4) See CPU usage rise (reported as /usr/bin/plasmashell process)
5) Reconnect Internet connection
6) Click Refresh again
7) CPU usage returns back to normal

It seems that the CPU usage even rises over time.

It would be better if the widget had a way to determine there is no Internet connection and stopped trying to refresh. Even just the spinning animation itself is distracting.
